# centos-lamp
# Based on CentOS 7

FROM centos:7

#
# UPDATE PACKAGES
#
RUN yum update -y

#
# Add Epel Mirror
#
RUN yum install -y epel-release

#
# TOOLS
#
RUN yum install -y curl wget unzip yum-utils python-setuptools

#
# APACHE
#
RUN yum install -y httpd

#
# PHP
#
RUN yum -y install https://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum-config-manager --enable remi-php74
RUN yum install -y php  php-cli php-devel php-fpm php-gd php-json php-mbstring php-mysqlnd php-pdo php-pear 

# Install composer
WORKDIR /tmp
RUN curl -sS https://getcomposer.org/installer | php
RUN mv /tmp/composer.phar /usr/local/bin/composer
RUN chmod +x /usr/local/bin/composer

## CLEAN UP
RUN package-cleanup --dupes
RUN package-cleanup --cleandupes
RUN yum clean all

## edit centos zone
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

EXPOSE 80

#
# Start httpd in foreground
#
CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
